spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://192.168.1.103/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
server:
  context-path: /sell

wechat:
  mpAppId: wx75eab88f02a2e739
  mpAppSecret: 4c64c995ac89aae39629c5f8e9244dfd